### ISSUE TITLE
Responsive sizing

### ISSUE THREAD

**Issue by Stanzilla** [paulirish/lite-youtube-embed#74]
I currently use these to responsively size the video:

```css
.video-container {
  position: relative;
  width: 100%;
  height: 0;
  padding-bottom: 56.25%;
}

.video-embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 0;
}
```

which is the de-facto best practice to do so, correct me if I'm wrong please.

Any way this could be integrated into lite-youtube-embed itself?

**Comment by shawnfromportland** [comment]
@Stanzilla @paulirish simply commenting out [this line](https://github.com/paulirish/lite-youtube-embed/blob/master/src/lite-yt-embed.css#L9) in source allowed my lite-youtube-embed's to work perfectly in my particular layout. I attempted to override that style in my own stylesheet loaded afterwards with:
```
lite-youtube {
    max-width: none !important;
}
```
or
``` 
lite-youtube {
    max-width: 100% !important;
}
```
but neither solution worked and the embed was still limited to 750px. 

for now i will run lite-youtube-embed with the commented out source line 9 indicated above.

**Comment by paulirish** [comment]
hmmmm... i don't see a reason why `lite-youtube { max-width: none !important;}` wouldn't work. it should.

i added this style not too long ago because it was HUGE on my test pages. and that seemed wasteful.   

but i agree if someone can't clear that max-width then we have problems.

**Comment by paulovieira** [comment]
I was able to override `lite-youtube { max-width: ... }` without any problem.

Still, I agree with @Stanzilla that a video embed should  have 100% width by default. I think that would be a better developer experience.

What about changing those test pages so that the embeds are inside a small container?

**Comment by srflp** [comment]
If using tailwindcss, you can use `!max-w-full` class on the lite-youtube component to make it responsive

**Comment by paulirish** [comment]
> Still, I agree with @Stanzilla that a video embed should have 100% width by default.

The youtube iframe doesn't do 100% width by default. Therefore this drop-in replacement won't.   

-------

The solution to this is a basic style:

```css
lite-youtube {
  max-width: 100%;
}
```

I don't see why this [didn't work](https://github.com/paulirish/lite-youtube-embed/issues/74#issuecomment-868002080) for you, but perhaps some selector specificity issues?
